Replace popsicle with isomorphic-fetch
brh55/eth-price pull request #4
Opened 2017-06-11 08:30 UTC by radiovisual

This keeps the application running as expected, but also fixes the problem where running the tests is failing (possibly) due to nock + popsicle.

It also increases code coverage from 83% to 100%.

2017-06-11 16:11 UTC, brh55 requested changes
Nice fetch is a great choice. Take a look at my comments and tell me what you think. 👏

2017-06-11 16:11 UTC, brh55 commented on cli.js
> +const input = cli.input.map(item => item.replace(/,\s+/g, '')).join(',');
Looks like the same is logic is happening in the API(LOC 7), you should be able to just turn the array to a string and pass it to the API to format.

2017-06-11 16:11 UTC, brh55 commented on package.json
> +    "isomorphic-fetch": "^2.2.1",
Looks like it needs a tab or space

2017-06-11 18:38 UTC, radiovisual commented on cli.js
> +const input = cli.input.map(item => item.replace(/,\s+/g, '')).join(',');
yes, you are right. No need to do this in more than one place.

2017-06-11 18:53 UTC, radiovisual commented on package.json
> +    "isomorphic-fetch": "^2.2.1",
Weird, I added in the correct whitespace, but this comment isn't being shown as outdated. It should have been fixed in my last commit.

2017-06-11 19:04 UTC, radiovisual commented
I think I made all the changes you requested. Although it seems GitHub disagrees that I completed them, since it still says there is a change pending. Did I miss anything, or did we find a bug in GitHub's reporting? 😆

2017-06-11 22:07 UTC, brh55 approved these changes
Looks good!

2017-06-11 22:08 UTC, merged

2017-06-11 22:11 UTC, brh55 commented
I'm thinking we could strip out the API to a core module such as (crypto-price) and make several different CLI for different cryptos. Since I would like to do one for Lisk as well.

2017-06-11 23:20 UTC, radiovisual commented
> I'm thinking we could strip out the API to a core module such as (crypto-price) and make several different CLI for different cryptos. Since I would like to do one for Lisk as well.

I like this idea. I would like to be able to compare different crypto-currencies from the command line, but also have the freedom to write applications in node to consume this data as well. I am happy to help if you want me to extract the API.

2017-06-12 02:21 UTC, brh55 commented
I'm thinking we could make an org? Something crypto related, and perhaps move this over to it?

2017-06-12 07:08 UTC, radiovisual commented
> I'm thinking we could make an org? Something crypto related, and perhaps move this over to it? 

I would love that, and I would be happy to help building crypto-related modules. Please start the org and send me an invite!

2017-06-12 14:49 UTC, brh55 commented
@radiovisual Have any good names to call the org? lol

2017-06-12 14:59 UTC, radiovisual commented
@brh55 

If not already taken:

- crypto
- crypt

Only if its cryptocoin-centric:

- cryptocoin (only if its cryptocoin-centric)
- cryptoin
- ccoin 

I also like:

- cryto (read "cry-dough")
- krypto
- kriptoin

Maybe I will think of something better later on...

2017-06-12 15:06 UTC, brh55 commented
Available Options:
- crypto-devs
- crydo
- cryptdoe
- dcryptos
- crypto-code
- krycode

2017-06-12 15:10 UTC, radiovisual commented
Dang, all the good names are taken. Looks like we will need to get creative. haha.

I like `crypto-code`, but `cryptocode` is already taken, and I think that could lead to some namespace confusion.

2017-06-12 15:11 UTC, radiovisual commented
Maybe we can find some cool keywords from the decentralized and cryptographic keyword space and find something unique that hasn't been taken yet, but still feels relevant.

2017-06-12 15:17 UTC, radiovisual commented
- crypt-chart
- crypt-space
- crypti
- cryp-tip
- cryptools
- crypline
- cryp-line
- crypterm
- cryp-term
- cryminal 🔫

2017-06-12 15:18 UTC, brh55 commented
Yeah, we might need a interesting name completely different from "crypto". Also crypto-craft is an option

2017-06-12 15:19 UTC, radiovisual commented
`crypto-craft` is cool.

2017-06-12 15:30 UTC, brh55 commented
Haha I just like the shortness of crypti 💃

2017-06-12 15:33 UTC, radiovisual commented
I really like `crypti` as well. 👍  😄  :taco:

2017-06-12 15:35 UTC, radiovisual commented
I like `crypto-craft` and `crypti` so far the best.

2017-06-12 15:36 UTC, brh55 commented
Invited you for crypti 🍡  👍

2017-06-12 15:37 UTC, radiovisual commented
Alright! Now we can get to work. :man_dancing: 🚀

2017-06-12 15:38 UTC, brh55 commented
Made you owner as well, feel free to re-word the org description and add a logo. 🎢

2017-06-12 15:39 UTC, radiovisual commented
> Made you owner as well, feel free to re-word the org description and add a logo

Ok, awesome. Thanks!

2017-06-12 15:53 UTC, radiovisual commented
So do you want a separate command line tool for each crypto currency, or one tool that can manage them all?

It would be cool if we had a tool that could compare cryptocurrencies like we pair currencies in Forex:

```
$ ccoin eth/usd, btc/usd
Converting...
   ETH/USD: 000.00
   BTC/USD: 0000.00
```

Or something like: `$ ccoin <from> <to>`

```
$ ccoin eth,btc usd,jpy
Converting...
   ETH/USD: 000.00
   ETH/JPY: 000.00
   BTC/USD: 0000.00
   BTC/JPY: 0000.00
```

Or even cooler, if you don't remember all the coin codes, you can have an interface that helps you decide:

```
$ ccoin
Which cryptocurrencies do you want?
  [x] Ethereum
  [ ] BitCoin

What currencies do you want to convert to?
 [x] American Dollar (USD)
 [ ] Japanese Yen (JPY)

ETH/USD: 000.00
```

2017-06-12 16:01 UTC, brh55 commented
Whew the last option is awesome. I'm thinking we have one core CLI / module that does both `$ ccoin <from> <to>`, and when it's blank it prompts the user. 

But we should also have a defaults, so when you run ccoin and it will always show your stored preferences.

```
$ ccoin
Which cryptocurrencies do you want?
  [x] Ethereum
  [ ] BitCoin

What currencies do you want to convert to?
 [x] American Dollar (USD)
 [ ] Japanese Yen (JPY)

Would you like to set default conversions? y/n

ETH/USD: 000.00
```

as well as: `$ ccoin btc usd,eth,ltc --save` || `$ ccoin btc usd,eth,ltc --set-default`

2017-06-12 16:09 UTC, brh55 commented
The only downside is cryptocompare supports 100 different currencies hahaha (https://www.cryptocompare.com/api/data/coinlist/)

2017-06-12 16:10 UTC, radiovisual commented
Ok cool. I like that the ability to save preferences or profiles.

So I could possibly do something like (assuming I had a profile saved called `yen-stuff`) :

```
$ ccoin -p yen-stuff
```
where `-p` is the flag to load a saved profile?

Or if I wanted to create a profile called `yen-stuff`:

```
$ ccoin btc,jpy, usd,jpy --save-as=yen-stuff
```

and then finally, the prompt could also ask if you want to save your settings as a profile:

```
Which cryptocurrencies do you want?
  [x] Ethereum
  [ ] BitCoin

What currencies do you want to convert to?
 [x] American Dollar (USD)
 [ ] Japanese Yen (JPY)

Do you want to save these settings? (Y/n) Y
What would you like to name this profile? yen-stuff
Ok, now you can run this profile with `$ ccoin -p yen-stuff`
```

Something like that?

2017-06-12 16:12 UTC, radiovisual commented
> The only downside is cryptocompare supports 100 different currencies hahaha 

Yeah, baby-steps! 🍼  haha.

2017-06-14 09:25 UTC, radiovisual commented
@brh55 has work begun on crypti/ccoin? I see the repo has been made, but nothing has been committed?

2017-06-14 14:32 UTC, brh55 commented
@radiovisual Ah yes, I was going to commit the base repo from the generator but got side-tracked.

2017-06-14 15:53 UTC, radiovisual commented
Ok, cool. I will monitor the progress and pitch in where needed. Are you going to make a separate module for the API calls to cryptocompare, or just hard-wire it into ccoin?

2017-06-14 16:48 UTC, brh55 commented
I was thinking of making ccoin the core, but I could perhaps leverage [this module](https://github.com/exodusmovement/cryptocompare)?

2017-06-14 17:32 UTC, radiovisual commented
yeah, I like that plan. I would use that module you pointed to since it already has the API we need. 😎